---
title: "Twitter Customer Segmentation"
author: "Pedro Ivo Rivas"
date: "8/13/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
market = read.csv("C:/Users/pivo/Desktop/UT MSBA/Summer 2019/Predictive Models/STA380/data/social_marketing.csv", row.names=1)

library(tidyr)
library(mosaic)
library(dplyr)
library(reshape2)
library(ggplot2)


market <- cbind(market[,2:4],market[6:36])
market_scale = market
cormat <- round(cor(market), 2)
melted_cormat <- melt(cormat)

ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) +
  geom_tile() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.6))

#market_scale = sweep(market, MARGIN = 1, FUN = '/', STATS = rowSums(market[,]))
market_scale = market/rowSums(market)
market_scale = scale(market_scale, center = TRUE, scale = FALSE)

# for (i in 1:nrow(market)){
#   market_scale[i,] = market[i, ]/sum(market[i,])
#   market_scale[i,'total'] = sum(market[i,])
# }
# 
# View(market_scale)
# 
# for (i in 1:nrow(market)){
# market_scale[i,'total'] = market_scale[i,'total']/sum(market_scale[,'total'])
#}

market_distance_matrix = dist(market_scale, method='euclidean')
hier_tree = hclust(market_distance_matrix, method='complete')
clusters = cutree(hier_tree, k=5)

summary(factor(clusters))
```

# PCA

```{r}
pc5 = prcomp(market_scale, scale=FALSE, rank=5)
plot(pc5)
loadings = pc5$rotation
scores = pc5$x
#head(market_scale)
pairs(scores)

```

```{r}
o1 = order(loadings[,1], decreasing=TRUE)
o2 = order(loadings[,2], decreasing=TRUE)
o3 = order(loadings[,3], decreasing=TRUE)
o4 = order(loadings[,4], decreasing=TRUE)
o5 = order(loadings[,5], decreasing=TRUE)

print('C1')
print(colnames(market_scale)[head(o1,4)])
print(colnames(market_scale)[tail(o1,4)])
print('C2')
print(colnames(market_scale)[head(o2,4)])
print(colnames(market_scale)[tail(o2,4)])
print('C3')
print(colnames(market_scale)[head(o3,4)])
print(colnames(market_scale)[tail(o3,4)])
print('C4')
print(colnames(market_scale)[head(o4,4)])
print(colnames(market_scale)[tail(o4,4)])
print('C5')
print(colnames(market_scale)[head(o5,4)])
print(colnames(market_scale)[tail(o5,4)])

```

```{r}
print(summary(pc5))
```

```{r}

```

