---
title: "GBuild"
author: "Rocco Lange"
date: "8/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
```


```{r}
greenbuildings = read.csv('greenbuildings.csv')
```

```{r}
library(mosaic)
library(tidyverse)
```

```{r}
gb1 = mutate(greenbuildings,
       rent_diff_cluster = ((Rent / cluster_rent ) - 1))
```

```{r}
View(gb1)
```
```{r}
attach(gb1)
```


```{r}
g2 = ggplot(gb1, aes(x=rent_diff_cluster))

g2 + geom_density(aes(fill=factor(green_rating)), alpha=0.6) +
  labs(title="Density plot", 
       subtitle="Rent Difference vs Paid Utilities",
       caption="Source: greenbuilding data set in R",
       x="Rent Difference from Cluster Rent",
       fill="Green Rating") +
       facet_grid(net)
```

```{r}
# gb1 = mutate(gb1, class_type = class_a*2 + class_b)
# g2 = ggplot(gb1, aes(x=rent_diff_cluster))
# attach(gb1)
# g2 + geom_density(aes(fill=factor(green_rating)), alpha=0.6) +
#   labs(title="Density plot", 
#        subtitle="Rent Difference vs Paid Utilities",
#        caption="Source: greenbuilding data set in R",
#        x="Rent Difference from Cluster Rent",
#        fill="Green Rating") +
#        facet_grid(class_type ~ net)
```

```{python}
import pandas as pd
df = pd.read_csv('greenbuildings.csv')
print(df.head())
```

```{r}
nongreen = subset(gb1, green_rating == 0)
green = subset(gb1, green_rating == 1)
```


```{r}
gb1$rent_diff_cluster = gb1$Rent/gb1$rent_diff_cluster
```

```{r}
gb1$class_type = gb1$class_a*2 + gb1$class_b
```


```{r}
ggplot(data = gb1, aes(x = gb1$Rent)) +
  geom_density(aes(fill=factor(gb1$green_rating)), alpha=0.7) + 
  labs(title="Density plot", 
       subtitle="Rent vs Paid Utilities and Class",
       caption="Source: greenbuilding data set in R",
       x="Rent",
       fill="Green Rating") +
  facet_grid(net~class_type) 

```


```{r}
gb1$green_rating = ifelse(gb1$green_rating==1, "Green", "Non-Green")

View(gb1)
```


```{r}
gb1$class_type = ifelse(gb1$class_type==0, "Class C", ifelse(gb1$class_type==1, "Class B", "Class A"))
```

```{r}
gb1$class_type = ifelse(gb1$class_type=="CLass B", "Class B", gb1$class_type)
```


```{r}
gb1$net = ifelse(gb1$net==1,"Utilities Paid","Utilities Not Paid")
```


```{r}
nongreen = subset(gb1, green_rating == "Non-Green")
```
```{r}
green = subset(gb1, green_rating == "Green")
```


```{r}
ggplot(data = gb1,mapping = aes(x=gb1$leasing_rate, y=gb1$Rent, color=gb1$green_rating),alpha=0.8) +
  geom_point() + 
  scale_color_brewer(palette="Dark2") +
  labs(title="Scatter plot", 
       subtitle="Leasing Rate vs Rent split by Paid Utilities and Class",
       caption="Source: greenbuilding data set in R",
       x="Leasing Rate", y="Rent",
       color="Green Rating") + 
  facet_grid(gb1$net~gb1$class_type)
```



```{r}
ggplot(data = gb1, mapping = aes(x=gb1$size, y=gb1$Rent, color=gb1$green_rating),alpha=0.7) +
  geom_point() +  
  scale_color_brewer(palette="Dark2") +
  labs(title="Scatter plot", 
       subtitle="Size vs Rent split by Paid Utilities and Class",
       caption="Source: greenbuilding data set in R",
       x="Size", y="Rent",
       color="Green Rating") + 
  facet_grid(gb1$net~gb1$class_type)
```

```{r}
ggplot(data = green, mapping = aes(x=green$size, y=green$Rent, color=green$green_rating),alpha=0.7) +
  geom_point() +  
  scale_color_brewer(palette="Dark2") +
  labs(title="Scatter plot", 
       subtitle="Size vs Rent split by Paid Utilities and Class",
       caption="Source: greenbuilding data set in R",
       x="Size", y="Rent",
       color="Green Rating") + 
  facet_grid(green$net~green$class_type) +
  theme(axis.text.x = element_text(angle=90, vjust=0.6))
```

```{r}
ggplot(data = nongreen, mapping = aes(x=nongreen$size, y=nongreen$Rent, color=nongreen$green_rating),alpha=0.7) +
  geom_point(color='orange') +  
  scale_color_brewer(palette="Dark2") +
  labs(title="Scatter plot", 
       subtitle="Size vs Rent split by Paid Utilities and Class",
       caption="Source: greenbuilding data set in R",
       x="Size", y="Rent",
       color="Green Rating") + 
  facet_grid(nongreen$net~nongreen$class_type) +
  theme(axis.text.x = element_text(angle=90, vjust=0.6))
```

